apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "archetype-backend.name" . }}
  labels:
    {{- include "archetype-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "archetype-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "archetype-backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "archetype-backend.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
