apiVersion: v1
kind: Service
metadata:
  name: {{ include "archetype-backend.name" . }}
  labels:
    {{- include "archetype-backend.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "archetype-backend.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
