apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ocirepository-archetype-backend.yaml
  - helmrelease-archetype-backend.yaml
  - ocirepository-archetype-backend-values.yaml
  - kustomization-archetype-backend-values.yaml
